# Generated by Django 4.1.2 on 2023-03-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('cabinet', models.IntegerField()),
                ('status', models.IntegerField()),
                ('user', models.CharField(max_length=124)),
                ('firstname', models.CharField(max_length=124)),
                ('lastname', models.CharField(max_length=124)),
                ('assigned', models.CharField(max_length=124)),
                ('assigned_firstname', models.CharField(max_length=124)),
                ('assigned_lastname', models.CharField(max_length=124)),
            ],
        ),
    ]
